version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - user-service